import { v4 as uuid4 } from "uuid";

function ChillHop() {
  return [
    {
      number: 1,
      name: "Lollipop",
      artist: "Gafur, JONY",
      audio: "https://mp3uk.net/mp3/files/gafur-jony-lollipop-mp3.mp3",
      cover:
        "https://mp3uk.net/uploads/posts/2020-07/thumbs/1594370526_gafur.jpg",
      color: ["#3CC99C", "#117A9D"],
      active: true,
      id: uuid4(),
    },
    {
      number: 2,
      name: "Лилии",
      artist: "Мот, JONY",
      audio: "https://mp3uk.net/mp3/files/mot-jony-lilii-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#409C1B", "#2D005F"],
      active: false,
      id: uuid4(),
    },
    {
      number: 3,
      name: "Пустота",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-pustota-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#91D77C", "#D75D07"],
      active: false,
      id: uuid4(),
    },
    {
      number: 4,
      name: "Без тебя я не я",
      artist: "JONY, HammAli, Navai",
      audio:
        "https://mp3uk.net/mp3/files/jony-hammali-navai-bez-tebya-ya-ne-ya-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#CCD9C0", "#C97A45"],
      active: false,
      id: uuid4(),
    },
    {
      number: 5,
      name: "Ты беспощадна",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-ty-besposhadna-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#E6CCE3", "#9672A5"],
      active: false,
      id: uuid4(),
    },
    {
      number: 6,
      name: "Мир сошёл с ума",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-mir-soshyol-s-uma-mp3.mp3",
      cover:
        "https://mp3uk.net/uploads/posts/2020-08/thumbs/1597962965_jony-.jpg",
      color: ["#2CE7DB", "#48CB53"],
      active: false,
      id: uuid4(),
    },
    {
      number: 7,
      name: "Комета",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-kometa-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#111CFC", "#B450F2"],
      active: false,
      id: uuid4(),
    },
    {
      number: 8,
      name: "Балкон",
      artist: "ELMAN, JONY",
      audio: "https://mp3uk.net/mp3/files/elman-jony-balkon-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#31B8E2", "#68B538"],
      active: false,
      id: uuid4(),
    },
    {
      number: 9,
      name: "Ты Пари",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-ty-pari-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#6B3644", "#C2D363"],
      active: false,
      id: uuid4(),
    },
    {
      number: 10,
      name: "Босс",
      artist: "Jony, The Limba",
      audio: "https://mp3uk.net/mp3/files/jony-the-limba-boss-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#FDE96D", "#E956A4"],
      active: false,
      id: uuid4(),
    },
    {
      number: 11,
      name: "Ты беспощадна",
      artist: "Jony, Navai",
      audio: "https://mp3uk.net/mp3/files/jony-navai-ty-besposhadna-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#872A2E", "#CBB90D"],
      active: false,
      id: uuid4(),
    },
    {
      number: 12,
      name: "Наверно, Ты Меня Не Помнишь",
      artist: "Jony, Hammali",
      audio:
        "https://mp3uk.net/mp3/files/jony-hammali-naverno-ty-menya-ne-pomnish-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#2C884B", "#02BDB1"],
      active: false,
      id: uuid4(),
    },
    {
      number: 13,
      name: "Камин",
      artist: "EMIN, JONY",
      audio: "https://mp3uk.net/mp3/files/emin-jony-kamin-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#F4D027", "#BB62E7"],
      active: false,
      id: uuid4(),
    },
    {
      number: 14,
      name: "Как любовь твою понять?",
      artist: "JONY, ANNA ASTI",
      audio:
        "https://mp3uk.net/mp3/files/jony-anna-asti-kak-lyubov-tvoyu-ponyat-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#959731", "#148479"],
      active: false,
      id: uuid4(),
    },
    {
      number: 15,
      name: "Эта Любовь Свела Меня С Ума (Dndm Remix)",
      artist: "Zohid, Jony",
      audio:
        "https://mp3uk.net/mp3/files/zohid-jony-eta-lyubov-svela-menya-s-uma-dndm-remix-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#18E284", "#C5DA28"],
      active: false,
      id: uuid4(),
    },
    {
      number: 16,
      name: "Love Your Voice",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-love-your-voice-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#C46D67", "#4E8061"],
      active: false,
      id: uuid4(),
    },
    {
      number: 17,
      name: "Падаю - Поймай",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-padayu-pojmaj-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#FA2239", "#65601B"],
      active: false,
      id: uuid4(),
    },
    {
      number: 18,
      name: "Пустой стакан",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-pustoj-stakan-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#154E59", "#4F5624"],
      active: false,
      id: uuid4(),
    },
    {
      number: 19,
      name: "Камнепад",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-kamnepad-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#D313F9", "#3F0116"],
      active: false,
      id: uuid4(),
    },
    {
      number: 20,
      name: "Аллея",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-alleya-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#18A3E5", "#64145E"],
      active: false,
      id: uuid4(),
    },
    {
      number: 21,
      name: "На Сиреневой Луне",
      artist: "Jony",
      audio: "https://mp3uk.net/mp3/files/jony-na-sirenevoj-lune-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#4D1F6A", "#A58469"],
      active: false,
      id: uuid4(),
    },
    {
      number: 22,
      name: "Лунная Ночь",
      artist: "Emin, JONY",
      audio: "https://mp3uk.net/mp3/files/emin-jony-lunnaya-noch-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#DAD42B", "#E629DD"],
      active: false,
      id: uuid4(),
    },
    {
      number: 23,
      name: "Звезда",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-zvezda-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#8FED02", "#E14203"],
      active: false,
      id: uuid4(),
    },
    {
      number: 24,
      name: "Небесные Розы",
      artist: "Jony",
      audio: "https://mp3uk.net/mp3/files/jony-nebesnye-rozy-mp3.mp3",
      cover:
        "https://mp3uk.net/uploads/posts/2020-08/thumbs/1597963482_jony-.jpg",
      color: ["#357C8C", "#6F1273"],
      active: false,
      id: uuid4(),
    },
    {
      number: 25,
      name: "Мадам",
      artist: "Jony, Andro",
      audio: "https://mp3uk.net/mp3/files/jony-andro-madam-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#73DDD8", "#9A0A86"],
      active: false,
      id: uuid4(),
    },
    {
      number: 26,
      name: "Титры",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-titry-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#B98449", "#F1A9E1"],
      active: false,
      id: uuid4(),
    },
    {
      number: 27,
      name: "Воздушный Сарафан",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-vozdushnyj-sarafan-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#62C04B", "#12278E"],
      active: false,
      id: uuid4(),
    },
    {
      number: 28,
      name: "Неужели ты моя",
      artist: "Bahh Tee, JONY",
      audio:
        "https://mp3uk.net/mp3/files/bahh-tee-jony-neuzheli-ty-moya-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#FF1680", "#4E2198"],
      active: false,
      id: uuid4(),
    },
    {
      number: 29,
      name: "Черемушка",
      artist: "Andro, Jony",
      audio: "https://mp3uk.net/mp3/files/andro-jony-cheremushka-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#61A8F4", "#AB032B"],
      active: false,
      id: uuid4(),
    },
    {
      number: 30,
      name: "Френдзона",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-frendzona-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#C7689C", "#B6512A"],
      active: false,
      id: uuid4(),
    },
    {
      number: 31,
      name: "А За Окном Дожди",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-a-za-oknom-dozhdi-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#959086", "#DCD364"],
      active: false,
      id: uuid4(),
    },
    {
      number: 32,
      name: "Blue Eyes",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-blue-eyes-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#85F6D8", "#78DE72"],
      active: false,
      id: uuid4(),
    },
    {
      number: 33,
      name: "Мир зеленого цвета",
      artist: "Леонид Агутин, JONY",
      audio:
        "https://mp3uk.net/mp3/files/leonid-agutin-jony-mir-zelenogo-cveta-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#53AD49", "#3D950E"],
      active: false,
      id: uuid4(),
    },
    {
      number: 34,
      name: "Все решено",
      artist: "Jony",
      audio: "https://mp3uk.net/mp3/files/jony-vse-resheno-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#B454F0", "#F61B65"],
      active: false,
      id: uuid4(),
    },
    {
      number: 35,
      name: "Танцуй со мной летай ай ай ай",
      artist: "Jony",
      audio:
        "https://mp3uk.net/mp3/files/jony-tancuj-so-mnoj-letaj-aj-aj-aj-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#2716C1", "#585F2E"],
      active: false,
      id: uuid4(),
    },
    {
      number: 36,
      name: "Уйдешь",
      artist: "Rakhim, Jony",
      audio: "https://mp3uk.net/mp3/files/rakhim-jony-ujdesh-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#99BFD6", "#C0D4A1"],
      active: false,
      id: uuid4(),
    },
    {
      number: 37,
      name: "Лали",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-lali-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#63E4BE", "#755E8C"],
      active: false,
      id: uuid4(),
    },
    {
      number: 38,
      name: "Завороженный закатом",
      artist: "Jony",
      audio: "https://mp3uk.net/mp3/files/jony-zavorozhennyj-zakatom-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#7BFBAC", "#F28F35"],
      active: false,
      id: uuid4(),
    },
    {
      number: 39,
      name: "Лето и точка (Новый альбом 2023)",
      artist: "JONY",
      audio:
        "https://mp3uk.net/mp3/files/jony-leto-i-tochka-novyj-albom-2023-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#E4C993", "#FB2C9C"],
      active: false,
      id: uuid4(),
    },
    {
      number: 40,
      name: "Давай на ты",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-davaj-na-ty-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#0C0E94", "#07B0DF"],
      active: false,
      id: uuid4(),
    },
    {
      number: 41,
      name: "Героям Посвящается",
      artist:
        "Григорий Лепс, Jony, Emin, Artik, Asti, Стас Михайлов, Николай Басков",
      audio:
        "https://mp3uk.net/mp3/files/grigorij-leps-jony-emin-artik-asti-stas-mihajlov-nikolaj-baskov-geroyam-posvyashaetsya-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#89C57F", "#F8927F"],
      active: false,
      id: uuid4(),
    },
    {
      number: 42,
      name: "Заворожённый",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-zavorozhyonnyj-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#944015", "#7039A7"],
      active: false,
      id: uuid4(),
    },
    {
      number: 43,
      name: "Небесные Розы (Lavrushkin & Delay Remix)",
      artist: "Jony",
      audio:
        "https://mp3uk.net/mp3/files/jony-nebesnye-rozy-lavrushkin-delay-remix-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#6E7E86", "#996930"],
      active: false,
      id: uuid4(),
    },
    {
      number: 44,
      name: "Omg",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-omg-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#FF07B1", "#30A7DC"],
      active: false,
      id: uuid4(),
    },
    {
      number: 45,
      name: "Ты меня пленила",
      artist: "JONY",
      audio:
        "https://mp3uk.net/mp3/files/jony-vse-moi-rany-tvoya-nagrada-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#ED194E", "#6BB220"],
      active: false,
      id: uuid4(),
    },
    {
      number: 46,
      name: "Сени Севдим яр",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-seni-sevdim-yar-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#439C90", "#138C3F"],
      active: false,
      id: uuid4(),
    },
    {
      number: 47,
      name: "Признаю, с тобой я мог коснуться до луны",
      artist: "JONY, ANNA ASTI",
      audio:
        "https://mp3uk.net/mp3/files/jony-anna-asti-priznayu-s-toboj-ya-mog-kosnutsya-do-luny-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#80340E", "#4E6B1D"],
      active: false,
      id: uuid4(),
    },
    {
      number: 48,
      name: "УЛЕТАЮ",
      artist: "ANNA ASTI, JONY",
      audio: "https://mp3uk.net/mp3/files/anna-asti-jony-uletayu-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#8CFF94", "#926EDC"],
      active: false,
      id: uuid4(),
    },
    {
      number: 49,
      name: "Ты беспощадна (Slow remix)",
      artist: "Jony",
      audio:
        "https://mp3uk.net/mp3/files/jony-ty-besposhadna-slow-remix-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#B757B1", "#55B096"],
      active: false,
      id: uuid4(),
    },
    {
      number: 50,
      name: "Believe",
      artist: "Дима Билан, Jony",
      audio: "https://mp3uk.net/mp3/files/dima-bilan-jony-believe-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#9D3195", "#FC0192"],
      active: false,
      id: uuid4(),
    },
    {
      number: 51,
      name: "Дай мне побыть одному",
      artist: "JONY",
      audio: "https://mp3uk.net/mp3/files/jony-daj-mne-pobyt-odnomu-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#ED2D11", "#9DD58E"],
      active: false,
      id: uuid4(),
    },
    {
      number: 52,
      name: "Холода",
      artist: "Jony",
      audio: "https://mp3uk.net/mp3/files/jony-holoda-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#F793E4", "#A33093"],
      active: false,
      id: uuid4(),
    },
    {
      number: 53,
      name: "Черемушка  (Yura Sychev, Shted Radio Remix)",
      artist: "Andro, Jony",
      audio:
        "https://mp3uk.net/mp3/files/andro-jony-cheremushka-yura-sychev-shted-radio-remix-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#946B43", "#B18815"],
      active: false,
      id: uuid4(),
    },
    {
      number: 54,
      name: "Районы-Кварталы (DJ Tarantino Remix)",
      artist: "Звери",
      audio:
        "https://mp3uk.net/mp3/files/zveri-rajony-kvartaly-dj-tarantino-remix-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#E91CCC", "#190A8A"],
      active: false,
      id: uuid4(),
    },
    {
      number: 55,
      name: "Лали (DJ Prezzplay & DJ Insane Radio Edit)",
      artist: "Jony",
      audio:
        "https://mp3uk.net/mp3/files/jony-lali-dj-prezzplay-amp-dj-insane-radio-edit-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#E087E9", "#60BDD0"],
      active: false,
      id: uuid4(),
    },
    {
      number: 1,
      name: "FXRGET MY NAME",
      artist: "KUTE, Scarlxrd",
      audio: "https://mp3uk.net/mp3/files/kute-scarlxrd-fxrget-my-name-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#B1E1FE", "#09CBA4"],
      active: false,
      id: uuid4(),
    },
    {
      number: 2,
      name: "Always Want Me",
      artist: "DVRST, Scarlxrd",
      audio:
        "https://mp3uk.net/mp3/files/dvrst-scarlxrd-always-want-me-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#D6A27F", "#833FEF"],
      active: false,
      id: uuid4(),
    },
    {
      number: 3,
      name: "AUTUMN TREES",
      artist: "Scarlxrd, Corpse, Kxrdhell",
      audio:
        "https://mp3uk.net/mp3/files/scarlxrd-corpse-kxrdhell-autumn-trees-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#B49985", "#695BB4"],
      active: false,
      id: uuid4(),
    },
    {
      number: 4,
      name: "MISA MISA!",
      artist: "CORPSE, Scarlxrd, Kordhell",
      audio:
        "https://mp3uk.net/mp3/files/corpse-scarlxrd-kordhell-misa-misa-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#8EA82A", "#7FE723"],
      active: false,
      id: uuid4(),
    },
    {
      number: 5,
      name: "Let the Wxrld Burn",
      artist: "Scarlxrd",
      audio: "https://mp3uk.net/mp3/files/scarlxrd-let-the-wxrld-burn-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#8A10B1", "#8FD6DB"],
      active: false,
      id: uuid4(),
    },
    {
      number: 6,
      name: "FXRTUNE",
      artist: "Scarlxrd",
      audio: "https://mp3uk.net/mp3/files/scarlxrd-fxrtune-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#6E0BE5", "#1347E5"],
      active: false,
      id: uuid4(),
    },
    {
      number: 7,
      name: "C. V FREESTYLE",
      artist: "Scarlxrd",
      audio: "https://mp3uk.net/mp3/files/scarlxrd-c-v-freestyle-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#0C4B54", "#A68FFA"],
      active: false,
      id: uuid4(),
    },
    {
      number: 8,
      name: "FFS FREESTYLE.",
      artist: "scarlxrd",
      audio: "https://mp3uk.net/mp3/files/scarlxrd-ffs-freestyle-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#CB1299", "#922DD9"],
      active: false,
      id: uuid4(),
    },
    {
      number: 9,
      name: "ESCAPE.",
      artist: "Scarlxrd",
      audio: "https://mp3uk.net/mp3/files/scarlxrd-escape-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#C50806", "#DA25D2"],
      active: false,
      id: uuid4(),
    },
    {
      number: 10,
      name: "CXNCERN.",
      artist: "Scarlxrd",
      audio: "https://mp3uk.net/mp3/files/scarlxrd-cxncern-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#3C310C", "#88FDDC"],
      active: false,
      id: uuid4(),
    },
    {
      number: 1,
      name: "Патрон",
      artist: "Miyagi, Andy Panda",
      audio: "https://mp3uk.net/mp3/files/miyagi-andy-panda-patron-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#8E4E5D", "#E7D224"],
      active: false,
      id: uuid4(),
    },
    {
      number: 2,
      name: "Там ревели горы",
      artist: "Miyagi, Andy Panda",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-andy-panda-tam-reveli-gory-mp3.mp3",
      cover:
        "https://mp3uk.net/uploads/posts/2020-07/thumbs/1594934414_tam-reveli.jpg",
      color: ["#EEA5ED", "#55BBE7"],
      active: false,
      id: uuid4(),
    },
    {
      number: 3,
      name: "Minor",
      artist: "Miyagi, Andy Panda",
      audio: "https://mp3uk.net/mp3/files/miyagi-andy-panda-minor-mp3.mp3",
      cover:
        "https://mp3uk.net/uploads/posts/2020-07/thumbs/1594934630_minor.jpg",
      color: ["#41C874", "#2AA38C"],
      active: false,
      id: uuid4(),
    },
    {
      number: 4,
      name: "Yamakasi (Альбом)",
      artist: "Miyagi, Andy Panda",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-andy-panda-yamakasi-novyj-albom-mp3.mp3",
      cover:
        "https://mp3uk.net/uploads/posts/2020-07/thumbs/1594938311_yamakasi.jpg",
      color: ["#08F992", "#564044"],
      active: false,
      id: uuid4(),
    },
    {
      number: 5,
      name: "Brooklyn",
      artist: "Miyagi, Andy Panda, TumaniYO",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-andy-panda-tumaniyo-brooklyn-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#79181B", "#CB0B71"],
      active: false,
      id: uuid4(),
    },
    {
      number: 6,
      name: "Marmalade",
      artist: "Miyagi, Andy Panda, Mav-D",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-andy-panda-mav-d-marmalade-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#DC248C", "#25AB95"],
      active: false,
      id: uuid4(),
    },
    {
      number: 7,
      name: "Where Are You",
      artist: "Ollane, Miyagi, Andy Panda",
      audio:
        "https://mp3uk.net/mp3/files/ollane-miyagi-andy-panda-where-are-you-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#02A0A3", "#30A005"],
      active: false,
      id: uuid4(),
    },
    {
      number: 8,
      name: "Fire Man",
      artist: "Miyagi, Эндшпиль",
      audio: "https://mp3uk.net/mp3/files/miyagi-endshpil-fire-man-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#851381", "#D564B9"],
      active: false,
      id: uuid4(),
    },
    {
      number: 9,
      name: "Utopia",
      artist: "Miyagi, Andy Panda",
      audio: "https://mp3uk.net/mp3/files/miyagi-andy-panda-utopia-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#EF9911", "#7D9D5F"],
      active: false,
      id: uuid4(),
    },
    {
      number: 10,
      name: "Не Жаль",
      artist: "104, Miyagi, Скриптонит",
      audio:
        "https://mp3uk.net/mp3/files/104-miyagi-skriptonit-ne-zhal-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#810006", "#419A40"],
      active: false,
      id: uuid4(),
    },
    {
      number: 11,
      name: "HATTORI (Новый альбом 2022)",
      artist: "Мияги, Эндшпиль",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-endshpil-hattori-novyj-albom-2022-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#EE02F7", "#9E1948"],
      active: false,
      id: uuid4(),
    },
    {
      number: 12,
      name: "Малиновый рассвет",
      artist: "MiyaGi, Эндшпиль",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-endshpil-malinovyj-rassvet-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#2DF081", "#539BF3"],
      active: false,
      id: uuid4(),
    },
    {
      number: 13,
      name: "Свора",
      artist: "Miyagi, Andy Panda, Cкриптонит",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-andy-panda-ckriptonit-svora-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#1EDA02", "#36D7B2"],
      active: false,
      id: uuid4(),
    },
    {
      number: 14,
      name: "All The Time",
      artist: "MiyaGi, Andy Panda",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-andy-panda-all-the-time-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#B72751", "#9421E1"],
      active: false,
      id: uuid4(),
    },
    {
      number: 15,
      name: "Не жалея",
      artist: "Miyagi, Andy Panda",
      audio: "https://mp3uk.net/mp3/files/miyagi-andy-panda-ne-zhaleya-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#68AE40", "#1C2B27"],
      active: false,
      id: uuid4(),
    },
    {
      number: 16,
      name: "Freeman",
      artist: "Miyagi, Andy Panda",
      audio: "https://mp3uk.net/mp3/files/miyagi-andy-panda-freeman-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#2D9C4E", "#08B98B"],
      active: false,
      id: uuid4(),
    },
    {
      number: 17,
      name: "Корабли",
      artist: "Miyagi",
      audio: "https://mp3uk.net/mp3/files/miyagi-korabli-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#C0613E", "#F487EE"],
      active: false,
      id: uuid4(),
    },
    {
      number: 18,
      name: "Silhouette",
      artist: "Miyagi, Эндшпиль",
      audio: "https://mp3uk.net/mp3/files/miyagi-endshpil-silhouette-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#1D02B8", "#F9FFBD"],
      active: false,
      id: uuid4(),
    },
    {
      number: 19,
      name: "Караван",
      artist: "MiyaGi, Andy Panda",
      audio: "https://mp3uk.net/mp3/files/miyagi-andy-panda-karavan-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#85B56C", "#7C5BD5"],
      active: false,
      id: uuid4(),
    },
    {
      number: 20,
      name: "Оттепель",
      artist: "Miyagi, Andy Panda, Tumaniyo",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-andy-panda-tumaniyo-ottepel-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#9AE324", "#6D1143"],
      active: false,
      id: uuid4(),
    },
    {
      number: 21,
      name: "По Полям",
      artist: "MiyaGi, Эндшпиль",
      audio: "https://mp3uk.net/mp3/files/miyagi-endshpil-po-polyam-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#785E48", "#4E7358"],
      active: false,
      id: uuid4(),
    },
    {
      number: 22,
      name: "Tantra",
      artist: "Miyagi, Andy Panda",
      audio: "https://mp3uk.net/mp3/files/miyagi-andy-panda-tantra-mp3.mp3",
      cover:
        "https://mp3uk.net/uploads/posts/2020-07/thumbs/1594935204_tantra.jpg",
      color: ["#4AACBC", "#C1C86B"],
      active: false,
      id: uuid4(),
    },
    {
      number: 23,
      name: "Yamakasi",
      artist: "Miyagi, Andy Panda",
      audio: "https://mp3uk.net/mp3/files/miyagi-andy-panda-yamakasi-mp3.mp3",
      cover:
        "https://mp3uk.net/uploads/posts/2020-07/thumbs/1594934208_yamakasi.jpg",
      color: ["#D72032", "#FBF809"],
      active: false,
      id: uuid4(),
    },
    {
      number: 24,
      name: "Барадачи",
      artist: "Miyagi, Andy Panda",
      audio: "https://mp3uk.net/mp3/files/miyagi-andy-panda-baradachi-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#ECED1D", "#01E7AF"],
      active: false,
      id: uuid4(),
    },
    {
      number: 25,
      name: "Brooklyn (Wertus remix)",
      artist: "Miyagi",
      audio: "https://mp3uk.net/mp3/files/wertus-miyagi-brooklyn-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#72BE0F", "#CFBE45"],
      active: false,
      id: uuid4(),
    },
    {
      number: 26,
      name: "Kosandra",
      artist: "Miyagi, Andy Panda",
      audio: "https://mp3uk.net/mp3/files/miyagi-andy-panda-kosandra-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#DA7296", "#148890"],
      active: false,
      id: uuid4(),
    },
    {
      number: 27,
      name: "Стать легендой",
      artist: "Miyagi, Andy Panda, Типси Тип",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-andy-panda-tipsi-tip-stat-legendoj-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#C830EE", "#1371F9"],
      active: false,
      id: uuid4(),
    },
    {
      number: 28,
      name: "Touch the Sky",
      artist: "Ollane, Miyagi",
      audio: "https://mp3uk.net/mp3/files/ollane-miyagi-touch-the-sky-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#BCB741", "#D38E94"],
      active: false,
      id: uuid4(),
    },
    {
      number: 29,
      name: "Временно",
      artist: "Miyagi, Эндшпиль",
      audio: "https://mp3uk.net/mp3/files/miyagi-endshpil-vremenno-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#1BD54A", "#26D84B"],
      active: false,
      id: uuid4(),
    },
    {
      number: 30,
      name: "Мало Нам",
      artist: "Miyagi, Andy Panda",
      audio: "https://mp3uk.net/mp3/files/miyagi-andy-panda-malo-nam-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#0F0688", "#2A8F19"],
      active: false,
      id: uuid4(),
    },
    {
      number: 31,
      name: "Буревестник",
      artist: "Miyagi, Andy Panda",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-andy-panda-burevestnik-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#B30403", "#98FE0E"],
      active: false,
      id: uuid4(),
    },
    {
      number: 32,
      name: "Не теряя",
      artist: "Miyagi, Эндшпиль",
      audio: "https://mp3uk.net/mp3/files/miyagi-endshpil-ne-teryaya-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#A46DAE", "#660BFF"],
      active: false,
      id: uuid4(),
    },
    {
      number: 33,
      name: "Темнота",
      artist: "Mav-D, Miyagi, Andy Panda",
      audio:
        "https://mp3uk.net/mp3/files/mav-d-miyagi-andy-panda-temnota-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#AD5AE9", "#98B37F"],
      active: false,
      id: uuid4(),
    },
    {
      number: 34,
      name: "Saloon",
      artist: "Miyagi, Эндшпиль",
      audio: "https://mp3uk.net/mp3/files/miyagi-endshpil-saloon-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#237D9B", "#8FDBDD"],
      active: false,
      id: uuid4(),
    },
    {
      number: 35,
      name: "Самая",
      artist: "MiyaGi, Эндшпиль, Amigo",
      audio: "https://mp3uk.net/mp3/files/miyagi-endshpil-amigo-samaya-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#3644FE", "#2C592E"],
      active: false,
      id: uuid4(),
    },
    {
      number: 36,
      name: "Bismarck",
      artist: "Miyagi, Tumaniyo, Kadi",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-tumaniyo-kadi-bismarck-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#72FCA2", "#3C6F24"],
      active: false,
      id: uuid4(),
    },
    {
      number: 37,
      name: "Atlant",
      artist: "Miyagi, Andy Panda",
      audio: "https://mp3uk.net/mp3/files/miyagi-andy-panda-atlant-mp3.mp3",
      cover:
        "https://mp3uk.net/uploads/posts/2020-07/thumbs/1594935600_atlant.jpg",
      color: ["#8781F9", "#CFBF41"],
      active: false,
      id: uuid4(),
    },
    {
      number: 38,
      name: "Небо",
      artist: "Miyagi",
      audio: "https://mp3uk.net/mp3/files/miyagi-nebo-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#B189E7", "#2689A9"],
      active: false,
      id: uuid4(),
    },
    {
      number: 39,
      name: "Bounty",
      artist: "Miyagi, Эндшпиль",
      audio: "https://mp3uk.net/mp3/files/miyagi-endshpil-bounty-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#78D0B8", "#10D283"],
      active: false,
      id: uuid4(),
    },
    {
      number: 40,
      name: "Психопатия",
      artist: "Miyagi, Andy Panda",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-andy-panda-psihopatiya-mp3.mp3",
      cover:
        "https://mp3uk.net/uploads/posts/2020-07/thumbs/1594935313_psihopatiya.jpg",
      color: ["#6ABE0C", "#945D57"],
      active: false,
      id: uuid4(),
    },
    {
      number: 41,
      name: "Need me",
      artist: "Miyagi, Эндшпиль",
      audio: "https://mp3uk.net/mp3/files/miyagi-endshpil-need-me-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#1DA836", "#B85B5F"],
      active: false,
      id: uuid4(),
    },
    {
      number: 42,
      name: "Время не делай из меня ты демона",
      artist: "Miyagi, Эндшпиль",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-endshpil-vremya-ne-delaj-iz-menya-ty-demona-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#736B2C", "#DD0869"],
      active: false,
      id: uuid4(),
    },
    {
      number: 43,
      name: "Medicine",
      artist: "Miyagi, Andy Panda",
      audio: "https://mp3uk.net/mp3/files/miyagi-andy-panda-medicine-mp3.mp3",
      cover:
        "https://mp3uk.net/uploads/posts/2020-07/thumbs/1594936105_medicine.jpg",
      color: ["#B4D18E", "#706D1F"],
      active: false,
      id: uuid4(),
    },
    {
      number: 44,
      name: "Endorphin",
      artist: "Miyagi, Andy Panda",
      audio: "https://mp3uk.net/mp3/files/miyagi-andy-panda-endorphin-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#F1258F", "#142C10"],
      active: false,
      id: uuid4(),
    },
    {
      number: 45,
      name: "Prayers",
      artist: "KADI, Miyagi",
      audio: "https://mp3uk.net/mp3/files/kadi-miyagi-prayers-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#0541D6", "#47A9E8"],
      active: false,
      id: uuid4(),
    },
    {
      number: 46,
      name: "Монолит",
      artist: "Скриптонит, Miyagi, Масло Черного Тмина",
      audio:
        "https://mp3uk.net/mp3/files/skriptonit-miyagi-maslo-chernogo-tmina-monolit-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#5A7544", "#CB4F72"],
      active: false,
      id: uuid4(),
    },
    {
      number: 47,
      name: "Saloon",
      artist: "Miyagi, Andy Panda",
      audio: "https://mp3uk.net/mp3/files/miyagi-andy-panda-saloon-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#AE2A78", "#769D45"],
      active: false,
      id: uuid4(),
    },
    {
      number: 48,
      name: "Нет Войне",
      artist: "Miyagi",
      audio: "https://mp3uk.net/mp3/files/miyagi-net-vojne-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#BEE5E7", "#4AB8BB"],
      active: false,
      id: uuid4(),
    },
    {
      number: 49,
      name: "Колизей",
      artist: "Miyagi, Эндшпиль",
      audio: "https://mp3uk.net/mp3/files/miyagi-endshpil-kolizej-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#5E4062", "#CB5D12"],
      active: false,
      id: uuid4(),
    },
    {
      number: 50,
      name: "Untouchable",
      artist: "Miyagi, Эндшпиль, Рем Дигга",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-endshpil-rem-digga-untouchable-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#2C233B", "#AA1ABB"],
      active: false,
      id: uuid4(),
    },
    {
      number: 51,
      name: "Ночь",
      artist: "Miyagi, Эндшпиль",
      audio: "https://mp3uk.net/mp3/files/miyagi-endshpil-noch-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#F66BFA", "#68B0C2"],
      active: false,
      id: uuid4(),
    },
    {
      number: 52,
      name: "Angel",
      artist: "MiyaGi",
      audio: "https://mp3uk.net/mp3/files/miyagi-angel-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#44C48C", "#E827A5"],
      active: false,
      id: uuid4(),
    },
    {
      number: 53,
      name: "Расскажи",
      artist: "MiyaGi, Amigo",
      audio: "https://mp3uk.net/mp3/files/miyagi-amigo-rasskazhi-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#1AFAD6", "#24E7B0"],
      active: false,
      id: uuid4(),
    },
    {
      number: 54,
      name: "Туда",
      artist: "Эндшпиль, TumaniYO",
      audio: "https://mp3uk.net/mp3/files/endshpil-tumaniyo-tuda-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#23495E", "#696533"],
      active: false,
      id: uuid4(),
    },
    {
      number: 55,
      name: "Listen To Your Heart",
      artist: "Miyagi, Эндшпиль",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-endshpil-listen-to-your-heart-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#546CD2", "#490A90"],
      active: false,
      id: uuid4(),
    },
    {
      number: 56,
      name: "Texture",
      artist: "Miyagi",
      audio: "https://mp3uk.net/mp3/files/miyagi-texture-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#2C293B", "#4E3AC0"],
      active: false,
      id: uuid4(),
    },
    {
      number: 57,
      name: "Напалм",
      artist: "Скриптонит, Miyagi, Andy Panda",
      audio:
        "https://mp3uk.net/mp3/files/skriptonit-miyagi-andy-panda-napalm-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#39FA67", "#4A3873"],
      active: false,
      id: uuid4(),
    },
    {
      number: 58,
      name: "Shar Iz Ognya",
      artist: "MiyaGi, Andy Panda",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-andy-panda-shar-iz-ognya-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#A6AA0D", "#435D48"],
      active: false,
      id: uuid4(),
    },
    {
      number: 59,
      name: "Мой Гарлем",
      artist: "Miyagi, Amigo",
      audio: "https://mp3uk.net/mp3/files/miyagi-amigo-moj-garlem-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#0B3CCE", "#321050"],
      active: false,
      id: uuid4(),
    },
    {
      number: 60,
      name: "Меломанам",
      artist: "Miyagi",
      audio: "https://mp3uk.net/mp3/files/miyagi-melomanam-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#D87512", "#81B941"],
      active: false,
      id: uuid4(),
    },
    {
      number: 61,
      name: "Jumanji",
      artist: "Andy Panda, TumaniYO, Miyagi",
      audio:
        "https://mp3uk.net/mp3/files/andy-panda-tumaniyo-miyagi-jumanji-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#1C30B7", "#348C72"],
      active: false,
      id: uuid4(),
    },
    {
      number: 62,
      name: "Fire of Freedom",
      artist: "Da NeL, Miyagi, Andy Panda",
      audio:
        "https://mp3uk.net/mp3/files/da-nel-miyagi-andy-panda-fire-of-freedom-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#C846B2", "#2DA80F"],
      active: false,
      id: uuid4(),
    },
    {
      number: 63,
      name: "Dance Up (Scott Rill Remix)",
      artist: "TumaniYO, Miyagi, Эндшпиль",
      audio:
        "https://mp3uk.net/mp3/files/tumaniyo-miyagi-endshpil-dance-up-scott-rill-remix-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#5CB3FB", "#729B33"],
      active: false,
      id: uuid4(),
    },
    {
      number: 64,
      name: "Давай Вали",
      artist: "Miyagi",
      audio: "https://mp3uk.net/mp3/files/miyagi-davaj-vali-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#212450", "#EFC882"],
      active: false,
      id: uuid4(),
    },
    {
      number: 65,
      name: "Silhouette (Pavelalt Remix)",
      artist: "Miyagi, Эндшпиль",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-endshpil-silhouette-pavelalt-remix-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#41374C", "#36218D"],
      active: false,
      id: uuid4(),
    },
    {
      number: 66,
      name: "Актёр",
      artist: "Miyagi",
      audio: "https://mp3uk.net/mp3/files/miyagi-aktyor-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#D30E37", "#CAFC7B"],
      active: false,
      id: uuid4(),
    },
    {
      number: 67,
      name: "Клевета",
      artist: "MiyaGi, Andy Panda, Namo Minigun",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-andy-panda-namo-minigun-kleveta-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#FAFF4D", "#D7AECA"],
      active: false,
      id: uuid4(),
    },
    {
      number: 68,
      name: "Meet me",
      artist: "Miyagi, Эндшпиль, Kadi",
      audio: "https://mp3uk.net/mp3/files/miyagi-endshpil-kadi-meet-me-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#E2FE77", "#A03C0E"],
      active: false,
      id: uuid4(),
    },
    {
      number: 69,
      name: "Салун последнего шанса",
      artist: "Miyagi, Andy Panda",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-andy-panda-salun-poslednego-shansa-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#015409", "#7E0C41"],
      active: false,
      id: uuid4(),
    },
    {
      number: 70,
      name: "Psychopathy",
      artist: "MiyaGi",
      audio: "https://mp3uk.net/mp3/files/miyagi-psychopathy-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#A72930", "#469DF3"],
      active: false,
      id: uuid4(),
    },
    {
      number: 71,
      name: "По полям (rakheemow remix 2023)",
      artist: "Miyagi, Эндшпиль",
      audio:
        "https://mp3uk.net/mp3/files/miyagi-endshpil-po-polyam-rakheemow-remix-2023-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#20D76E", "#0A5064"],
      active: false,
      id: uuid4(),
    },
    {
      number: 1,
      name: "На Нервах",
      artist: "Ислам Итляшев",
      audio: "https://mp3uk.net/mp3/files/islam-itlyashev-na-nervah-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#378226", "#11F981"],
      active: false,
      id: uuid4(),
    },
    {
      number: 2,
      name: "Хулиган",
      artist: "Ислам Итляшев, Султан Лагучев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-sultan-laguchev-huligan-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#84665F", "#C6B89D"],
      active: false,
      id: uuid4(),
    },
    {
      number: 3,
      name: "Ай-Яй-Яй (Дикая)",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-aj-yaj-yaj-dikaya-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#370FAB", "#DFB536"],
      active: false,
      id: uuid4(),
    },
    {
      number: 4,
      name: "Кобра",
      artist: "Ислам Итляшев",
      audio: "https://mp3uk.net/mp3/files/islam-itlyashev-kobra-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#52FF59", "#997EC1"],
      active: false,
      id: uuid4(),
    },
    {
      number: 5,
      name: "Она Любила Розы",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-ona-lyubila-rozy-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#751229", "#640C05"],
      active: false,
      id: uuid4(),
    },
    {
      number: 6,
      name: "Улетаю",
      artist: "Ислам Итляшев",
      audio: "https://mp3uk.net/mp3/files/islam-itlyashev-uletayu-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#A942D8", "#1F9D4F"],
      active: false,
      id: uuid4(),
    },
    {
      number: 7,
      name: "Сердце Не Ревнуй",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-serdce-ne-revnuj-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#B24E3B", "#0CAFD6"],
      active: false,
      id: uuid4(),
    },
    {
      number: 8,
      name: "Ресторан",
      artist: "Ислам Итляшев",
      audio: "https://mp3uk.net/mp3/files/islam-itlyashev-restoran-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#B0455F", "#874CBB"],
      active: false,
      id: uuid4(),
    },
    {
      number: 9,
      name: "Доля воровская",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-dolya-vorovskaya-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#DCC4D6", "#D8A17B"],
      active: false,
      id: uuid4(),
    },
    {
      number: 10,
      name: "Хищница",
      artist: "Ислам Итляшев",
      audio: "https://mp3uk.net/mp3/files/islam-itlyashev-hishnica-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#AA25CA", "#B93E7B"],
      active: false,
      id: uuid4(),
    },
    {
      number: 11,
      name: "Запомню навсегда твои глаза",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-zapomnyu-navsegda-tvoi-glaza-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#6CAE67", "#66E05C"],
      active: false,
      id: uuid4(),
    },
    {
      number: 12,
      name: "Пацаны На Стиле",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-pacany-na-stile-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#83AEDB", "#B53C6D"],
      active: false,
      id: uuid4(),
    },
    {
      number: 13,
      name: "Молодая",
      artist: "Ислам Итляшев",
      audio: "https://mp3uk.net/mp3/files/islam-itlyashev-molodaya-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#5FDD0D", "#DBC7BB"],
      active: false,
      id: uuid4(),
    },
    {
      number: 14,
      name: "Больше Не Нужна",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-bolshe-ne-nuzhna-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#2423E7", "#E54FC7"],
      active: false,
      id: uuid4(),
    },
    {
      number: 15,
      name: "На рахате",
      artist: "Ислам Итляшев, Султан Лагучев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-sultan-laguchev-na-rahate-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#A6B5F3", "#A85817"],
      active: false,
      id: uuid4(),
    },
    {
      number: 16,
      name: "Мирный, Красивый Край",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-mirnyj-krasivyj-kraj-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#DD3816", "#F9F49D"],
      active: false,
      id: uuid4(),
    },
    {
      number: 17,
      name: "Москва-Владивосток",
      artist: "Ислам Итляшев, Ирина Круг",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-irina-krug-moskva-vladivostok-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#D8FABF", "#CAF13D"],
      active: false,
      id: uuid4(),
    },
    {
      number: 18,
      name: "Мир или война",
      artist: "Khalif, Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/khalif-islam-itlyashev-mir-ili-voi-na-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#AE86F8", "#EFFB8C"],
      active: false,
      id: uuid4(),
    },
    {
      number: 19,
      name: "Лиса",
      artist: "Ислам Итляшев",
      audio: "https://mp3uk.net/mp3/files/islam-itlyashev-lisa-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#90FC2C", "#8D5E01"],
      active: false,
      id: uuid4(),
    },
    {
      number: 20,
      name: "Ты для меня",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-ty-dlya-menya-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#2AF609", "#120F48"],
      active: false,
      id: uuid4(),
    },
    {
      number: 21,
      name: "Когда-Нибудь Растает Лед",
      artist: "Ислам Итляшев, Ирина Круг",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-irina-krug-kogda-nibud-rastaet-led-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#1457D5", "#AE5ED2"],
      active: false,
      id: uuid4(),
    },
    {
      number: 22,
      name: "Красивая",
      artist: "Ислам Итляшев",
      audio: "https://mp3uk.net/mp3/files/islam-itlyashev-krasivaya-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#1404F8", "#3AB397"],
      active: false,
      id: uuid4(),
    },
    {
      number: 23,
      name: "Сделан Из Стали",
      artist: "Ислам Итляшев, Султан Лагучев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-sultan-laguchev-sdelan-iz-stali-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#2EA262", "#172B4A"],
      active: false,
      id: uuid4(),
    },
    {
      number: 24,
      name: "Плохая (Новый альбом 2023)",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-plohaya-novyj-albom-2023-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#860A62", "#08043A"],
      active: false,
      id: uuid4(),
    },
    {
      number: 25,
      name: "Плохая",
      artist: "Ислам Итляшев",
      audio: "https://mp3uk.net/mp3/files/islam-itlyashev-plohaya-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#11FF1C", "#E98143"],
      active: false,
      id: uuid4(),
    },
    {
      number: 26,
      name: "Сумасшедшая",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-sumasshedshaya-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#70198E", "#47B991"],
      active: false,
      id: uuid4(),
    },
    {
      number: 27,
      name: "В селе родном",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-v-sele-rodnom-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#7B7FAA", "#1DE308"],
      active: false,
      id: uuid4(),
    },
    {
      number: 28,
      name: "Не Стреляй",
      artist: "Ислам Итляшев",
      audio: "https://mp3uk.net/mp3/files/islam-itlyashev-ne-strelyaj-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#BAA654", "#B2E262"],
      active: false,
      id: uuid4(),
    },
    {
      number: 29,
      name: "Горькая любовь",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-gorkaya-lyubov-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#56C385", "#A5B2F6"],
      active: false,
      id: uuid4(),
    },
    {
      number: 30,
      name: "Счастье Любит Тишину 2021",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-schaste-lyubit-tishinu-2021-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#9C5AD0", "#5B64D9"],
      active: false,
      id: uuid4(),
    },
    {
      number: 31,
      name: "Коварная",
      artist: "Ислам Итляшев",
      audio: "https://mp3uk.net/mp3/files/islam-itlyashev-kovarnaya-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#1B6244", "#24C894"],
      active: false,
      id: uuid4(),
    },
    {
      number: 32,
      name: "Странник",
      artist: "Ислам Итляшев",
      audio: "https://mp3uk.net/mp3/files/islam-itlyashev-strannik-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#240AF4", "#0D3457"],
      active: false,
      id: uuid4(),
    },
    {
      number: 33,
      name: "Девочка криминал",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-devochka-kriminal-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#658FF5", "#851AE9"],
      active: false,
      id: uuid4(),
    },
    {
      number: 34,
      name: "Моя",
      artist: "Ислам Итляшев",
      audio: "https://mp3uk.net/mp3/files/islam-itlyashev-moya-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#EB422E", "#319A8B"],
      active: false,
      id: uuid4(),
    },
    {
      number: 35,
      name: "Зачем Я Отпускаю",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-zachem-ya-otpuskayu-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#973A46", "#C04592"],
      active: false,
      id: uuid4(),
    },
    {
      number: 36,
      name: "Не люби",
      artist: "Ислам Итляшев",
      audio: "https://mp3uk.net/mp3/files/islam-itlyashev-ne-lyubi-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#F6CF29", "#416DAE"],
      active: false,
      id: uuid4(),
    },
    {
      number: 37,
      name: "Танцуешь со мной",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-tancuesh-so-mnoj-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#5EA370", "#6C2FFA"],
      active: false,
      id: uuid4(),
    },
    {
      number: 38,
      name: "Ты Полюбила Хулигана",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-ty-polyubila-huligana-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#5E87D1", "#7DB78F"],
      active: false,
      id: uuid4(),
    },
    {
      number: 39,
      name: "Тамара",
      artist: "Ислам Итляшев",
      audio: "https://mp3uk.net/mp3/files/islam-itlyashev-tamara-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#69F82B", "#EC22D9"],
      active: false,
      id: uuid4(),
    },
    {
      number: 40,
      name: "Не сожалею",
      artist: "Ислам Итляшев",
      audio: "https://mp3uk.net/mp3/files/islam-itlyashev-ne-sozhaleyu-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#4BEDA8", "#7F9B62"],
      active: false,
      id: uuid4(),
    },
    {
      number: 41,
      name: "Блатная романтика",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-blatnaya-romantika-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#570D5A", "#AAD9FC"],
      active: false,
      id: uuid4(),
    },
    {
      number: 42,
      name: "Она любила розы (DJ Prezzplay, DJ S7ven Remix)",
      artist: "Ислам Итляшев",
      audio:
        "https://mp3uk.net/mp3/files/islam-itlyashev-ona-lyubila-rozy-dj-prezzplay-dj-s7ven-remix-mp3.mp3",
      cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
      color: ["#5DB9CC", "#8C8915"],
      active: false,
      id: uuid4(),
    },
    // {
    //   number: 11,
    //   name: "Heart attack",
    //   artist: "Scarlxrd",
    //   audio:
    //     "https://muzfan.net/uploads/files/2019-01/1548591187_scarlxrd-heart-attack.mp3",
    //   cover: "https://mp3uk.net/templates/mp3uk/dleimages/no_image.jpg",
    //   color: ["#3F310C", "#28FDDC"],
    //   active: false,
    //   //download: "https://muzfan.net/engine/download.php?id=2190",
    //   id: uuid4(),
    // },
  ];
}

export default ChillHop;
